import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Design Elixir Studio",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/gek3qlq.css" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}